package com.idigital.epam.energy.service.DTO;

import com.sun.istack.NotNull;
import lombok.*;


@NoArgsConstructor
@AllArgsConstructor
@ToString
@Setter
@Getter

public class PaymentRequestFromResident {

    @NotNull/*(message = "description can not be null")*/
    private String description;
    //citizen card who send money id which generated by CITY_MANAGEMENT
    @NotNull /*(message = "citizen_card_id can not be null")*/
    private Long residentCardNumberSender;

}
