//package com.idigital.epam.energy.service.DTO;
//
//import com.sun.istack.NotNull;
//import lombok.*;
//
//@NoArgsConstructor
//@AllArgsConstructor
//@ToString
//@Setter
//@Getter
//
//public class TransferRequest {
//    //Name of every service
//    @NotNull(message = "serviceName can not be null")
//    private final String serviceName = "HOME_SERVICE"; // defined in the Account Service module
//    //Description to every payment
//    @NotNull(message = "description can not be null")
//    private String description;
//    //amount of payment
//    @NotNull(message = "amount can not be null")
//    private Integer amount;
//    //citizen card who send money id which generated by CITY_MANAGEMENT
//    @NotNull(message = "citizen_card_id can not be null")
//    private long citizenCardNumberSender;
//    //citizen card who receive money id which generated by CITY_MANAGEMENT
//    @NotNull(message = "citizen_card_id can not be null")
//    private long citizenCardNumberReceiver;
//    //time base generate token
//    @NotNull(message = "token can not be null")
//    private long token; // from HMAC
//
//}
